### PR TITLE
Add Support for Websockets

### PR DESCRIPTION
**Pull request by awcrotwell**
This PR adds support for websockets. When we discussed this, you mentioned you may prefer moving this code to a subclass or something. I don't quite remember. If this gets merged, cool. **However, this is a PR to document the code additions required to get websockets working.**

 I just tested this against crystal 1.0 & my previous websocket example. Let me know if you need anything else.

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
> When we discussed this, you mentioned you may prefer moving this code to a subclass or something.

Yea, I think it would be worth figuring out how websockets should work/be implemented longer term. 
I'd be easy to hack it in, but would be better to have a more throughout plan of attack.

Part of that plan would probably be having websockets be a dedicated `Response` type as most of the time websockets won't be used as part of a normal response.  I'm also not the biggest fan of relying on `upgrade_handler=` as it's not part of the public API of `HTTP::Server::Response`; which could lead to issues down the line.

I also think ideally we could leverage the `js` side of some existing lib but update/reimplement the server side of things to better support the listener/DI features of Athena.

**Comment by awcrotwell** [comment]
> I also think ideally we could leverage the `js` side of some existing lib but update/reimplement the server side of things to better support the listener/DI features of Athena.

I didn't think you would be interested in that. My goal was to get athena working with [cable](https://github.com/cable-cr/cable) so less code had to be maintained. While I prefer the [actioncable](https://github.com/rails/rails/tree/main/actioncable/app/javascript/action_cable) client, I believe [socket.io](https://socket.io/) is the most popular.

**Comment by Blacksmoke16** [comment]
@awcrotwell Would you mind creating an issue in place of this PR?  I think it would be better to have a more throughout plan of attack versus moving forward with this implementation.

**Comment by awcrotwell** [comment]
Sure not a problem!

**Pull request closed without merging**
