### PR TITLE
Don't include stack trace as part of 404 errors

### PR DESCRIPTION
**Pull request by Blacksmoke16**

### CODE REVIEW

**Comment by oprypin** [comment]
When?

**Comment by Blacksmoke16** [comment]
@oprypin I'm still not sure if this is the right approach.  Especially when its easily possible to custom when/how exceptions are logged.  E.x.

```cr
struct Athena::Routing::Listeners::Error
  protected def log_exception(exception : Exception, &block : -> String) : Nil
    # If the exception is a 404 error, log it without stack trace
    if exception.is_a? ART::Exceptions::NotFound
      LOGGER.warn { yield }
    else
      # Otherwise fallback on the default logic.
      previous_def(exception, &block)
    end
  end
end
```

**Comment by oprypin** [comment]
Wait, is a monkeypatch the official solution?

**Comment by Blacksmoke16** [comment]
@oprypin For simple things like this yea.  The listener was designed to allow for having that method redefined without affecting any logic other than logging.

Outside of simple things like this.  I.e. you want to have _total_ control over what happens when there is an exception, you'd be best off defining your exception listener and aliasing it to the default one.  E.g.

```cr
# Alias this to the default listener.
# This service will replace the other one.
@[ADI::Register(alias: Athena::Routing::Listeners::Error)]
struct CustomErrorListener
  include AED::EventListenerInterface

  def self.subscribed_events : AED::SubscribedEvents
    AED::SubscribedEvents{
      ART::Events::Exception => -50,
    }
  end

  def call(event : ART::Events::Exception, dispatcher : AED::EventDispatcherInterface) : Nil
    # Do what you want to handle the exception.
  end
end
```

**Comment by Blacksmoke16** [comment]
Going to close this as I think it's best each user customize logging to how they see fit; especially if they're making use of custom backends.

**Pull request closed without merging**
